seed: 100
epochs: 101
# want to log/plot the moments every E epochs
log_every: 20 
batch_size: 128
plot_dir: "/fast/slaing/adam_moment_plots/"

# AdamW parameters.... fused is faster
lr: 0.001
fused_optim: True
weight_decay: 0.1
beta1: 0.9
beta2: 0.999
dampening: 0.1
eps: 1.e-8

model: "simplelda"