seed: 100
epochs: 101
# want to log/plot the moments every E epochs.... (epochs + 1)% log_every = 0 gets best bang for buck
log_every: 10 

# AdamW parameters.... fused is faster
lr: 0.001
fused_optim: True
weight_decay: 0.1
beta1: 0.9
beta2: 0.999
dampening: 0.1
eps: 1.e-8
grad_clip: 1.0

model: "resnet18"